# Generated by Django 5.2.4 on 2025-10-03 04:21

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0005_groupmessage_file_alter_chatgroup_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='group_banners/'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
